name: caching

env:
  RANDA: $RANDOM

on:
  push:
  pull_request:

jobs:
  test_cache:
    runs-on: ubuntu-latest    
    steps:       
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cache-test
      with:
        path: cacheFolder
        key: cache-${{ github.run_id }}
        restore-keys: cache-
    - run: |
              echo RANDA= ${{ env.RANDA }} $RANDA
              echo RANDOM= $RANDOM
              echo job.container.id ${{ job.container.id }}
              echo job.container.network ${{ job.container.network }}
              echo github.run_id ${{ github.run_id }}
              echo github.run_number ${{ github.run_number }}
    - run: |
              mkdir -p cacheFolder
              [ -e  cacheFolder/foo.txt ] || echo "0" > cacheFolder/foo.txt
    - run: |
              value=$(cat cacheFolder/foo.txt)
              next_value=$((value + 1))
              echo "value: $value -> $next_value"
              echo "$next_value" > cacheFolder/foo.txt
               
