name: caching

env:
  RANDA: $RANDOM

on:
  push:
  pull_request:

jobs:
  test_cache:
    runs-on: ubuntu-latest    
    steps:       
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cache-test
      with:
        path: cacheFolder
#        key: cache-${{ github.run_id }}-${{ hashFiles('/proc/self/stat') }}
#        key: cache-${{ github.run_id }}-${{ hashFiles('.git/logs/HEAD') }}
#        key: cache-${{ env.INVOCATION_ID }}-${{ env.RUNNER_TRACKING_ID }}
        key: cache-${{ hashFiles('dev_random') }}
        restore-keys: cache-
    - run: |
              echo RANDA= ${{ env.RANDA }} $RANDA
              echo RANDOM= $RANDOM
              echo job.container.id ${{ job.container.id }}
              echo job.container.network ${{ job.container.network }}
              echo github.run_id ${{ github.run_id }}
              echo github.run_number ${{ github.run_number }}
              echo runner.temp ${{ runner.temp }}
              echo github.ref ${{ github.ref }}
              echo github.head_ref ${{ github.head_ref }}
              echo github.base_ref ${{ github.base_ref }}
    - run: env
    - run: |
              mkdir -p cacheFolder
              [ -e  cacheFolder/foo.txt ] || echo "0" > cacheFolder/foo.txt
    - run: |
              value=$(cat cacheFolder/foo.txt)
              next_value=$((value + 1))
              echo "value: $value -> $next_value"
              echo "$next_value" > cacheFolder/foo.txt
               
